'use client'

import { ChakraProvider } from '@chakra-ui/react'
import 'antd/dist/reset.css'
import { Provider } from 'react-redux'
import { store } from './store/store'

// export const metadata = {
// 	title: 'Online coffee',
// 	description: 'Generated by Next.js',
// }

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<body>
				<Provider store={store}>
					{/* <PersistGate loading={null} persistor={persistor}> */}
					<ChakraProvider>{children}</ChakraProvider>
					{/* </PersistGate> */}
				</Provider>
			</body>
		</html>
	)
}
