import { ChakraProvider } from '@chakra-ui/react'
import 'antd/dist/reset.css'

export const metadata = {
	title: 'Online coffee',
	description: 'Generated by Next.js',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<body>
				<ChakraProvider>{children}</ChakraProvider>
			</body>
		</html>
	)
}
